#!/usr/bin/env python3

import os

os.system("printf '\033]2;Arissploit Framework\a'")

# Import python modules
import traceback
import sys
import logging
import getopt
import csv

# Disable scapy warning
logging.getLogger("scapy.runtime").setLevel(logging.ERROR)

# Import getpath for lib path
from core import getpath

# Append lib path
sys.path.append(getpath.lib())

# Import core modules
from core import colors
from core import header
from core import shell
from core import scriptio
from core import getpath

# Print header
os.system("clear")
print(header.arissploit)
header.print_info()

# Exception handling

def fatalerror():
	print("\033[1;31m[-]\033[0m Unexpected error:")
	traceback.print_exc()
	print(colors.end)
	main(0, None)

# Start up shell

try:
	def main():
		try:
			shell.run()

		except SystemExit as e:
			sys.exit(e)

		except:
			fatalerror()

	if __name__ == '__main__':
		main()

# Exceptions

except KeyboardInterrupt:
	print()

except SystemExit as e:
	sys.exit(e)

except:
	fatalerror()
